<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#The-Basics-of-NumPy-Arrays" data-toc-modified-id="The-Basics-of-NumPy-Arrays-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>The Basics of NumPy Arrays</a></span><ul class="toc-item"><li><span><a href="#Create-Numpy-Array" data-toc-modified-id="Create-Numpy-Array-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Create Numpy Array</a></span><ul class="toc-item"><li><span><a href="#Create-Array-from-Python-Lists" data-toc-modified-id="Create-Array-from-Python-Lists-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Create Array from Python Lists</a></span></li><li><span><a href="#Creat-Numpy-Array-IO-with-files" data-toc-modified-id="Creat-Numpy-Array-IO-with-files-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Creat Numpy Array IO with files</a></span></li></ul></li><li><span><a href="#NumPy-Array-Attributes" data-toc-modified-id="NumPy-Array-Attributes-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>NumPy Array Attributes</a></span></li><li><span><a href="#Array-Indexing:-Accessing-Single-Elements" data-toc-modified-id="Array-Indexing:-Accessing-Single-Elements-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Array Indexing: Accessing Single Elements</a></span></li><li><span><a href="#Array-Slicing:-Accessing-Subarrays" data-toc-modified-id="Array-Slicing:-Accessing-Subarrays-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Array Slicing: Accessing Subarrays</a></span><ul class="toc-item"><li><span><a href="#One-dimensional-subarrays" data-toc-modified-id="One-dimensional-subarrays-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>One-dimensional subarrays</a></span></li><li><span><a href="#Multi-dimensional-subarrays" data-toc-modified-id="Multi-dimensional-subarrays-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>Multi-dimensional subarrays</a></span><ul class="toc-item"><li><span><a href="#Accessing-array-rows-and-columns" data-toc-modified-id="Accessing-array-rows-and-columns-1.4.2.1"><span class="toc-item-num">1.4.2.1&nbsp;&nbsp;</span>Accessing array rows and columns</a></span></li></ul></li><li><span><a href="#Subarrays-as-no-copy-views" data-toc-modified-id="Subarrays-as-no-copy-views-1.4.3"><span class="toc-item-num">1.4.3&nbsp;&nbsp;</span>Subarrays as no-copy views</a></span></li><li><span><a href="#Creating-copies-of-arrays" data-toc-modified-id="Creating-copies-of-arrays-1.4.4"><span class="toc-item-num">1.4.4&nbsp;&nbsp;</span>Creating copies of arrays</a></span></li></ul></li><li><span><a href="#Reshaping-of-Arrays" data-toc-modified-id="Reshaping-of-Arrays-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Reshaping of Arrays</a></span></li><li><span><a href="#Array-Concatenation-and-Splitting" data-toc-modified-id="Array-Concatenation-and-Splitting-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Array Concatenation and Splitting</a></span><ul class="toc-item"><li><span><a href="#Concatenation-of-arrays" data-toc-modified-id="Concatenation-of-arrays-1.6.1"><span class="toc-item-num">1.6.1&nbsp;&nbsp;</span>Concatenation of arrays</a></span></li><li><span><a href="#Splitting-of-arrays" data-toc-modified-id="Splitting-of-arrays-1.6.2"><span class="toc-item-num">1.6.2&nbsp;&nbsp;</span>Splitting of arrays</a></span></li></ul></li><li><span><a href="#Numpy-Array-Aggregation" data-toc-modified-id="Numpy-Array-Aggregation-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Numpy Array Aggregation</a></span></li></ul></li></ul></div>

# The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas ([Chapter 3](03.00-Introduction-to-Pandas.ipynb)) are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## Create Numpy Array

In [4]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Create Random Number Array

It's commonly used with random array generation by using `.random` method. 

In [33]:
np.random.rand(2, 3, 4)  #generate an 3-D array
np.random.randint(0, 10, 3) #generate random integers of np.int between low and high (low[, high, size])

array([[[0.25194099, 0.22116092, 0.25319119, 0.13105523],
        [0.01203622, 0.1154843 , 0.61848026, 0.97425621],
        [0.990345  , 0.4090541 , 0.16295443, 0.63876176]],

       [[0.49030535, 0.98940978, 0.06530421, 0.78323444],
        [0.2883985 , 0.24141862, 0.66250457, 0.24606318],
        [0.66585912, 0.51730852, 0.42408899, 0.55468781]]])

array([9, 3, 2])

With different methods appending, arrays with distributions could be generated.

In [29]:
np.random.uniform(0, 3, 4) #generate a uniform distributed array ([low, high, size])
np.random.poisson(1, 5)    #generate a poison distributed array ([lam, size])
np.random.normal(0, 1, 4)  #generate a normal(Gaussian) distributed array ([loc, scale, size])

array([2.48880674, 1.13710132, 0.28964883, 0.76841873])

array([1, 1, 1, 2, 1])

array([-0.41891835, -1.11437255,  0.60784169,  0.45723671])

### Create Array from Python Lists
Numpy arrays (1D) can be directly created from Python list. However, while python lists can hold different types, , NumPy array can only allow the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point) or give exception otherwise.

In [26]:
# integer array:
np.array([1, 4, 2, 5, 3])
a = np.array([1, 4, 2, 5, 3])
# array data type and shape
a.dtype
a.shape

# mixed type array, upcasting will be used
np.array([1, 4.4, 2.2, 5, 3])

# mixed type array, upcasting will be used
np.array([1, 4.4, 'string', 5, True])

# exception will throw when upcasting is not possible
np.array([1, 4.4, 'string', 5, list([1,2,3])])





array([1, 4, 2, 5, 3])

dtype('int32')

(5,)

array([1. , 4.4, 2.2, 5. , 3. ])

array(['1', '4.4', 'string', '5', 'True'], dtype='<U32')

ValueError: setting an array element with a sequence

### Create Numpy Array IO with files

Numpy arries can be created from txt and csv files.

In [ ]:
a = np.random.random((10,10))

np.save('numpyTest.txt',a,delimiter=',')
np.save('numpyTest.csv',a,delimiter=',')


b = np.genfromtxt("numpyTest.csv",delimiter=',')
c = np.genfromtxt("numpyTest.txt",delimiter=',')

## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [6]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

array([5, 0, 3, 3, 7, 9])

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

Another useful attribute is the ``dtype``, the data type of the array (which we discussed previously in [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb)):

In [ ]:
print("dtype:", x3.dtype)

Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [ ]:
x1

In [ ]:
x1[0]

In [ ]:
x1[4]

To index from the end of the array, you can use negative indices:

In [ ]:
x1[-1]

In [ ]:
x1[-2]

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [ ]:
x2

In [ ]:
x2[0, 0]

In [ ]:
x2[2, 0]

In [ ]:
x2[2, -1]

Values can also be modified using any of the above index notation:

In [ ]:
x2[0, 0] = 12
x2

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [ ]:
x1[0] = 3.14159  # this will be truncated!
x1

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x

In [ ]:
x[:5]  # first five elements

In [ ]:
x[5:]  # elements after index 5

In [ ]:
x[4:7]  # middle sub-array

In [ ]:
x[::2]  # every other element

In [ ]:
x[1::2]  # every other element, starting at index 1

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [ ]:
x[::-1]  # all elements, reversed

In [ ]:
x[5::-2]  # reversed every other from index 5

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [ ]:
x2

In [ ]:
x2[:2, :3]  # two rows, three columns

In [ ]:
x2[:3, ::2]  # all rows, every other column

Finally, subarray dimensions can even be reversed together:

In [ ]:
x2[::-1, ::-1]

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [ ]:
print(x2[:, 0])  # first column of x2

In [ ]:
print(x2[0, :])  # first row of x2

In the case of row access, the empty slice can be omitted for a more compact syntax:

In [30]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [31]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let's extract a $2 \times 2$ subarray from this:

In [32]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [33]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [35]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [36]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [38]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [39]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [40]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [41]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [42]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

We will see this type of transformation often throughout the remainder of the book.

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [43]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [44]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [45]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [46]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [48]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [49]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similary, ``np.dstack`` will stack arrays along the third axis.

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [50]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [51]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [53]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, ``np.dsplit`` will split arrays along the third axis.

## Numpy Array Aggregation

Numpy array aggregation includes calculation of sum, mean, minimum, maximum, and medium etc of a numpy array, either on the whole array or along a specific axis. 

In [11]:
# create a two-D numpy array
a = np.random.random((8,5))

a.sum()         # total sum
a.sum(axis = 0) # sum along the column
a.sum(axis = 1) # sum along the row 

a.min()         # minimum value of the whole array
a.min(axis = 0) # minimum values along the column
a.min(axis = 1) # minimum values along the row 

a.max()
a.cumsum()

a.mean()
a.std()


np.corrcoef(a, rowvar=True) # get the correlation matrix, each row is viewed as the samples from a random variable
np.corrcoef(a, rowvar=False)# get the correlation matrix, each column is viewed as the samples from a random variable

21.354645238880213

array([5.84705515, 3.44119396, 3.73422176, 3.77604608, 4.55612829])

array([2.99251934, 2.30443798, 1.34200172, 1.93145934, 2.62994058,
       3.09159881, 4.34234036, 2.7203471 ])

0.001141892793725674

array([0.33580799, 0.00114189, 0.12786121, 0.03853151, 0.16359443])

array([0.04889768, 0.01633625, 0.00114189, 0.03853151, 0.33580799,
       0.38747219, 0.62950862, 0.13657015])

0.9664592308989414

array([ 0.93228067,  0.98117835,  1.71837922,  2.22259765,  2.99251934,
        3.75486689,  3.77120314,  3.98342907,  4.73673328,  5.29695732,
        6.18460866,  6.18575055,  6.31361176,  6.47536461,  6.63895904,
        7.20758905,  7.96809244,  8.29851121,  8.33704272,  8.57041838,
        8.90622637,  9.50126814, 10.00621245, 10.74347632, 11.20035896,
       12.06277809, 12.51753494, 13.30854197, 13.69601417, 14.29195778,
       15.23315195, 16.19961119, 17.09360468, 17.7231133 , 18.63429814,
       19.19102241, 19.78907932, 19.92564947, 20.48964386, 21.35464524])

0.5338661309720053

0.293565183175429

array([[ 1.        ,  0.65459258,  0.67416585, -0.37560402, -0.65822853,
         0.75375075,  0.0203484 , -0.08047656],
       [ 0.65459258,  1.        ,  0.63493517, -0.56700086, -0.13859737,
         0.1221954 , -0.51385698,  0.34101387],
       [ 0.67416585,  0.63493517,  1.        ,  0.1850172 , -0.69933259,
         0.67978848,  0.18851245,  0.04053188],
       [-0.37560402, -0.56700086,  0.1850172 ,  1.        , -0.41353102,
         0.24566308,  0.80929669, -0.0362814 ],
       [-0.65822853, -0.13859737, -0.69933259, -0.41353102,  1.        ,
        -0.87408745, -0.74233431, -0.05131484],
       [ 0.75375075,  0.1221954 ,  0.67978848,  0.24566308, -0.87408745,
         1.        ,  0.53636028, -0.40840108],
       [ 0.0203484 , -0.51385698,  0.18851245,  0.80929669, -0.74233431,
         0.53636028,  1.        ,  0.03339166],
       [-0.08047656,  0.34101387,  0.04053188, -0.0362814 , -0.05131484,
        -0.40840108,  0.03339166,  1.        ]])